### PR TITLE
closes #371: fix weird error message for email verification in resend page

### LINKED ISSUE #371: Fix weird error when entering an invalid email in the resend email page for email verification
Image

### PR DESCRIPTION
**Pull request by anjiabdallah**
…ong token)

### CODE REVIEW

File: client/src/utils/requestServer.ts [hunk 1]
```diff
@@ -7,6 +7,51 @@ interface RequestServerOptions {
 
 export const SERVER_BASE_URL = import.meta.env.VITE_SERVER_BASE_URL ?? 'http://localhost:9090';
 
+function getServerErrorMessage(json: unknown) {
```
Comment (MarcHamamji) [inline client/src/utils/requestServer.ts]: I don't think we need all this logic here. As far as i know, the only way we're returning errors from the server is by the `message` property (the response is never an array or a string or another format, the error is never in an `error` field). So the contents of this function can be simplified.

(If we need this, keep it)

File: client/src/utils/requestServer.ts
Comment (MarcHamamji) [inline client/src/utils/requestServer.ts:1]: Do we really need the changes to this file? My guess would be that it's not needed. (If it is, it's fine keep them)

**Review by MarcHamamji — CHANGES_REQUESTED** [review]

**Review by MarcHamamji — APPROVED** [review]
