### PR TITLE
closes #356, #357, #352: fix date mismatches, disallow volunteers from withdrawing from postings that ended, send emails to volunteers when a posting they're enrolled in gets deleted

### LINKED ISSUE #352: Send emails to volunteers when a posting they're enrolled in gets deleted

### PR DESCRIPTION
**Pull request by LaraElKhatib**
in #256 the issue was that the date in the posting details was 1 day less than the actual start and end dates chosen by the organization (the date on the list/card and calendar were still correct)  in the example the start date chosen was actually feb 1 that's why we couldn't choose jan 31

### CODE REVIEW

File: client/src/pages/Posting.tsx [hunk 1]
```diff
@@ -1363,6 +1367,8 @@ function PostingPage() {
                       style="outline"
                       onClick={withdrawApplication}
                       loading={withdrawing}
+                      disabled={!canWithdrawFromPosting}
+                      title={canWithdrawFromPosting ? undefined : 'This posting has already ended.'}
```
Comment (anjiabdallah) [inline client/src/pages/Posting.tsx]: This title won't show because the button is disabled, maybe u can wrap it and put the title on the wrapper?

File: client/src/pages/Posting.tsx [hunk 2]
```diff
@@ -1375,6 +1381,8 @@ function PostingPage() {
                         style="outline"
                         onClick={withdrawApplication}
                         loading={withdrawing}
+                        disabled={!canWithdrawFromPosting}
+                        title={canWithdrawFromPosting ? undefined : 'This posting has already ended.'}
```
Comment (anjiabdallah) [inline client/src/pages/Posting.tsx]: here too

**Review by anjiabdallah — CHANGES_REQUESTED** [review]

File: server/src/api/routes/organization/posting.ts [hunk 3]
```diff
@@ -646,6 +666,19 @@ function createOrganizationPostingRouter(db: Kysely<Database>) {
...
+        await sendPostingDeletedEmail({
+          volunteerEmail: emailContext.volunteer_email,
+          volunteerName: `${emailContext.first_name} ${emailContext.last_name}`,
+          postingTitle: emailContext.posting_title,
+          organizationName: emailContext.organization_name,
+        });
+      } catch (err) {
+        console.error('Failed to send posting deleted email:', err);
+      }
+    }
```
Comment (anjiabdallah) [inline server/src/api/routes/organization/posting.ts]:
```ts
await Promise.allSettled(
  enrolledVolunteerEmailContexts.map(emailContext =>
    sendPostingDeletedEmail({
      volunteerEmail: emailContext.volunteer_email,
      volunteerName: `${emailContext.first_name} ${emailContext.last_name}`,
      postingTitle: emailContext.posting_title,
      organizationName: emailContext.organization_name,
    }).catch(err => {
      console.error(`Failed to send deletion notification email for posting ${postingId} to volunteer ${emailContext.volunteer_id}:`, err);
    })
  )
);
```
Maybe this is better because it sends all emails at once?

**Comment by anjiabdallah** [comment]
image
also now we're supposed to be able to choose the 30th of April but we're not allowed to
